// Code generated by foji 0.3, template: foji/openapi/auth.go.tpl; DO NOT EDIT.

package test

import (
	"strings"

	"github.com/bir/iken/fastutil"
	"github.com/valyala/fasthttp"
)

type AuthFunc = func(ctx *fasthttp.RequestCtx) (*User, error)
type Authenticator = func(key string) (*User, error)

func ApiKeyAuth(fn Authenticator) AuthFunc {
	return func(ctx *fasthttp.RequestCtx) (*User, error) {
		b := ctx.Request.Header.Peek("Authorization")
		if len(b) == 0 {
			return nil, fastutil.ErrUnauthorized
		}

		key := string(b)
		if strings.HasPrefix(key, "Bearer ") {
			key = key[7:]
		}

		return fn(key)
	}
}

func QueryKeyAuth(fn Authenticator) AuthFunc {
	return func(ctx *fasthttp.RequestCtx) (*User, error) {
		key, err := fastutil.QueryString(ctx, "key")
		if err != nil {
			return nil, err
		}

		return fn(key)
	}
}
