// Code generated by foji 0.3, template: foji/openapi/model.go.tpl; DO NOT EDIT.

package test

//  Error
//
// OpenAPI Component: Error
type Error struct {
	Code    int32  `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
}

func (p Error) Validate() error {
	return nil
}

//  NewPet
//
// OpenAPI Component: NewPet
type NewPet struct {
	// The pets name
	Name string `json:"name,omitempty"`
	Tag  string `json:"tag,omitempty"`
}

func (p NewPet) Validate() error {
	return nil
}

//  Pet
//
// OpenAPI Component: Pet
type Pet struct {
	NewPet
	ID int64 `json:"id,omitempty"`
}

func (p Pet) Validate() error {
	return nil
}
