// Code generated by foji {{ version }}, template: {{ templateFile }}; DO NOT EDIT.

package {{ .PackageName }}

import (
	"fmt"
	"time"
)

{{ range .DB }}
    {{ range .Tables }}

        {{- $table := .Name}}
        {{- $goName := case .Name -}}
        {{- $colNames := .Columns.ByOrdinal.Names }}
        {{- $pkNames := cases .PrimaryKeys.ByOrdinal.Names }}

		// {{$goName}} represents a record from '{{.Schema.Name}}.{{$table}}'.
		type {{$goName}} struct {
        {{- range .Columns.ByOrdinal }}
            {{ case .Name }} {{ $.GetType . $.PackageName }}
        {{- end }}
		}

		func (r {{$goName}}) String() string {
		return fmt.Sprintf( "{{$goName}}{
        {{- csv ($pkNames.Sprintf "%s:%%v" ) }}}",
        {{- csv ($pkNames.Sprintf "r.%s" ) }})
		}

    {{end}}
{{end}}

