version: "2"
run:
  tests: false
linters:
  default: all
  disable:
    - depguard
    - exhaustive
    - exhaustruct
    - gochecknoglobals
    - godot
    - lll
    - nlreturn
    - varnamelen
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 15
    godox:
      keywords:
        - NOTE
        - HACK
        - TEMP
        - FIX
        - FIXME
    varnamelen:
      max-distance: 10
      ignore-names:
        - ss
        - id
        - to
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-decls:
        - p Process
        - l zerolog.Logger
        - b []byte
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*_gen.go$
      - temp
formatters:
  enable:
    - goimports
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
      custom-order: true
  exclusions:
    generated: disable
