// Code generated by foji, template: foji/openapi/model.go.tpl; DO NOT EDIT.

package csvresponse

import (
	"encoding/json"
	"errors"
	"fmt"

	"github.com/bir/iken/validation"
	"github.com/google/uuid"
)

var ErrMissingRequiredField = errors.New("missing required field")

// Component Schemas

// Example
//
// OpenAPI Component Schema: Example
type Example struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name,omitempty,omitzero"`
}

func (p *Example) UnmarshalJSON(b []byte) error {
	var err error
	var requiredCheck map[string]any

	err = json.Unmarshal(b, &requiredCheck)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("Example.UnmarshalJSON Required: `%v`: %w", string(b), err)}
	}

	var validationErrors validation.Errors

	if _, ok := requiredCheck["id"]; !ok {
		validationErrors.Add("id", ErrMissingRequiredField)
	}

	if validationErrors != nil {
		return validationErrors.GetErr()
	}

	type ExampleJSON Example
	var parseObject ExampleJSON

	err = json.Unmarshal(b, &parseObject)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("Example.UnmarshalJSON: `%v`: %w", string(b), err)}
	}

	v := Example(parseObject)

	*p = v

	return nil
}

// Component Parameters

// Path Operations
