// Code generated by foji {{ version }}, template: {{ templateFile }}; DO NOT EDIT.

package {{ .Params.PackageName }}

import (
	"net/http"

	"github.com/fasthttp/router"
	"github.com/valyala/fasthttp"
)

var (
	strApplicationHTML = []byte("text/html")
	reDocHTML          = []byte(`<!DOCTYPE html>
<html>
  <head>
    <title>{{ .Params.Title }}</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">
    <style>
      body {
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <redoc spec-url='swagger.yaml' {{ .Params.RedocOptions }} ></redoc>
    <script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"> </script>
  </body>
</html>`)
)

func Register(r *router.Router) {
	r.GET("/docs", GetHTML)
	r.GET("/swagger.yaml", GetYaml)
}

func GetHTML(ctx *fasthttp.RequestCtx) {
	ctx.Response.Header.SetContentTypeBytes(strApplicationHTML)
	_, err := ctx.Write(reDocHTML)
	if err != nil {
		ctx.Error(err.Error(), http.StatusInternalServerError)
	}
}

func GetYaml(ctx *fasthttp.RequestCtx) {

{{- range .FileGroups }}
	{{- range .Files }}
		_, err := ctx.Write({{ case (goToken .Name) }}Bytes)
	{{- end -}}
{{end }}
	if err != nil {
		ctx.Error(err.Error(), http.StatusInternalServerError)
		return
	}
}
