// Code generated by foji, template: {{ templateFile }}; DO NOT EDIT.

package {{ .PackageName }}

import (
	"net/http"

	"github.com/bir/iken/httputil"
	"github.com/go-chi/chi/v5"
)

func Register(r chi.Router) {
	r.Get("/docs", httputil.RapiDoc(httputil.RapiDocOpts{SpecURL:"swagger.yaml"}))
	r.Get("/swagger.yaml", GetYaml)
}


func GetYaml(w http.ResponseWriter, r *http.Request) {

{{- range .FileGroups }}
	{{- range .Files }}
		_, err := w.Write({{ case (goToken .Name) }}Bytes)
	{{- end -}}
{{end }}
	if err != nil {
		httputil.ErrorHandler(w, r, err)

		return
	}
}
