// Generated by stringify. DO NOT EDIT!
// Generated from color.go for const Parameter.

package color

import "fmt"

// String implements the fmt.Stringer interface.
func (c Parameter) String() string {
	switch c {
	case Reset:
		return "Reset"
	case Bold:
		return "Bold"
	case Faint:
		return "Faint"
	case Italic:
		return "Italic"
	case Underline:
		return "Underline"
	case BlinkSlow:
		return "BlinkSlow"
	case BlinkRapid:
		return "BlinkRapid"
	case ReverseVideo:
		return "ReverseVideo"
	case Conceal:
		return "Conceal"
	case CrossedOut:
		return "CrossedOut"
	case PrimaryFont:
		return "PrimaryFont"
	case FgBlack:
		return "FgBlack"
	case FgRed:
		return "FgRed"
	case FgGreen:
		return "FgGreen"
	case FgYellow:
		return "FgYellow"
	case FgBlue:
		return "FgBlue"
	case FgMagenta:
		return "FgMagenta"
	case FgCyan:
		return "FgCyan"
	case FgWhite:
		return "FgWhite"
	case FgBBlack:
		return "FgBBlack"
	case FgBRed:
		return "FgBRed"
	case FgBGreen:
		return "FgBGreen"
	case FgBYellow:
		return "FgBYellow"
	case FgBBlue:
		return "FgBBlue"
	case FgBMagenta:
		return "FgBMagenta"
	case FgBCyan:
		return "FgBCyan"
	case FgBWhite:
		return "FgBWhite"
	case BgBlack:
		return "BgBlack"
	case BgRed:
		return "BgRed"
	case BgGreen:
		return "BgGreen"
	case BgYellow:
		return "BgYellow"
	case BgBlue:
		return "BgBlue"
	case BgMagenta:
		return "BgMagenta"
	case BgCyan:
		return "BgCyan"
	case BgWhite:
		return "BgWhite"
	case BgBBlack:
		return "BgBBlack"
	case BgBRed:
		return "BgBRed"
	case BgBGreen:
		return "BgBGreen"
	case BgBYellow:
		return "BgBYellow"
	case BgBBlue:
		return "BgBBlue"
	case BgBMagenta:
		return "BgBMagenta"
	case BgBCyan:
		return "BgBCyan"
	case BgBWhite:
		return "BgBWhite"
	default:
		return fmt.Sprintf("Parameter(%d)", c)
	}
}

// NewParameter returns a Parameter based on the given name. If the
// name doesn't match any value, the zero-value is returned.
func NewParameter(name string) Parameter {
	switch name {
	case "Reset":
		return Reset
	case "Bold":
		return Bold
	case "Faint":
		return Faint
	case "Italic":
		return Italic
	case "Underline":
		return Underline
	case "BlinkSlow":
		return BlinkSlow
	case "BlinkRapid":
		return BlinkRapid
	case "ReverseVideo":
		return ReverseVideo
	case "Conceal":
		return Conceal
	case "CrossedOut":
		return CrossedOut
	case "PrimaryFont":
		return PrimaryFont
	case "FgBlack":
		return FgBlack
	case "FgRed":
		return FgRed
	case "FgGreen":
		return FgGreen
	case "FgYellow":
		return FgYellow
	case "FgBlue":
		return FgBlue
	case "FgMagenta":
		return FgMagenta
	case "FgCyan":
		return FgCyan
	case "FgWhite":
		return FgWhite
	case "FgBBlack":
		return FgBBlack
	case "FgBRed":
		return FgBRed
	case "FgBGreen":
		return FgBGreen
	case "FgBYellow":
		return FgBYellow
	case "FgBBlue":
		return FgBBlue
	case "FgBMagenta":
		return FgBMagenta
	case "FgBCyan":
		return FgBCyan
	case "FgBWhite":
		return FgBWhite
	case "BgBlack":
		return BgBlack
	case "BgRed":
		return BgRed
	case "BgGreen":
		return BgGreen
	case "BgYellow":
		return BgYellow
	case "BgBlue":
		return BgBlue
	case "BgMagenta":
		return BgMagenta
	case "BgCyan":
		return BgCyan
	case "BgWhite":
		return BgWhite
	case "BgBBlack":
		return BgBBlack
	case "BgBRed":
		return BgBRed
	case "BgBGreen":
		return BgBGreen
	case "BgBYellow":
		return BgBYellow
	case "BgBBlue":
		return BgBBlue
	case "BgBMagenta":
		return BgBMagenta
	case "BgBCyan":
		return BgBCyan
	case "BgBWhite":
		return BgBWhite
	default:
		return Parameter(0)
	}
}
