// Generated by stringify. DO NOT EDIT!
// Generated from color.go for const Parameter.

package color

import "testing"

func TestParameterString(t *testing.T) {
	if Parameter(0).String() != "Reset" {
		t.Errorf("Parameter(0).String() != \"Reset\"")
	}
	if Parameter(1).String() != "Bold" {
		t.Errorf("Parameter(1).String() != \"Bold\"")
	}
	if Parameter(2).String() != "Faint" {
		t.Errorf("Parameter(2).String() != \"Faint\"")
	}
	if Parameter(3).String() != "Italic" {
		t.Errorf("Parameter(3).String() != \"Italic\"")
	}
	if Parameter(4).String() != "Underline" {
		t.Errorf("Parameter(4).String() != \"Underline\"")
	}
	if Parameter(5).String() != "BlinkSlow" {
		t.Errorf("Parameter(5).String() != \"BlinkSlow\"")
	}
	if Parameter(6).String() != "BlinkRapid" {
		t.Errorf("Parameter(6).String() != \"BlinkRapid\"")
	}
	if Parameter(7).String() != "ReverseVideo" {
		t.Errorf("Parameter(7).String() != \"ReverseVideo\"")
	}
	if Parameter(8).String() != "Conceal" {
		t.Errorf("Parameter(8).String() != \"Conceal\"")
	}
	if Parameter(9).String() != "CrossedOut" {
		t.Errorf("Parameter(9).String() != \"CrossedOut\"")
	}
	if Parameter(10).String() != "PrimaryFont" {
		t.Errorf("Parameter(10).String() != \"PrimaryFont\"")
	}
	if Parameter(30).String() != "FgBlack" {
		t.Errorf("Parameter(30).String() != \"FgBlack\"")
	}
	if Parameter(31).String() != "FgRed" {
		t.Errorf("Parameter(31).String() != \"FgRed\"")
	}
	if Parameter(32).String() != "FgGreen" {
		t.Errorf("Parameter(32).String() != \"FgGreen\"")
	}
	if Parameter(33).String() != "FgYellow" {
		t.Errorf("Parameter(33).String() != \"FgYellow\"")
	}
	if Parameter(34).String() != "FgBlue" {
		t.Errorf("Parameter(34).String() != \"FgBlue\"")
	}
	if Parameter(35).String() != "FgMagenta" {
		t.Errorf("Parameter(35).String() != \"FgMagenta\"")
	}
	if Parameter(36).String() != "FgCyan" {
		t.Errorf("Parameter(36).String() != \"FgCyan\"")
	}
	if Parameter(37).String() != "FgWhite" {
		t.Errorf("Parameter(37).String() != \"FgWhite\"")
	}
	if Parameter(90).String() != "FgBBlack" {
		t.Errorf("Parameter(90).String() != \"FgBBlack\"")
	}
	if Parameter(91).String() != "FgBRed" {
		t.Errorf("Parameter(91).String() != \"FgBRed\"")
	}
	if Parameter(92).String() != "FgBGreen" {
		t.Errorf("Parameter(92).String() != \"FgBGreen\"")
	}
	if Parameter(93).String() != "FgBYellow" {
		t.Errorf("Parameter(93).String() != \"FgBYellow\"")
	}
	if Parameter(94).String() != "FgBBlue" {
		t.Errorf("Parameter(94).String() != \"FgBBlue\"")
	}
	if Parameter(95).String() != "FgBMagenta" {
		t.Errorf("Parameter(95).String() != \"FgBMagenta\"")
	}
	if Parameter(96).String() != "FgBCyan" {
		t.Errorf("Parameter(96).String() != \"FgBCyan\"")
	}
	if Parameter(97).String() != "FgBWhite" {
		t.Errorf("Parameter(97).String() != \"FgBWhite\"")
	}
	if Parameter(40).String() != "BgBlack" {
		t.Errorf("Parameter(40).String() != \"BgBlack\"")
	}
	if Parameter(41).String() != "BgRed" {
		t.Errorf("Parameter(41).String() != \"BgRed\"")
	}
	if Parameter(42).String() != "BgGreen" {
		t.Errorf("Parameter(42).String() != \"BgGreen\"")
	}
	if Parameter(43).String() != "BgYellow" {
		t.Errorf("Parameter(43).String() != \"BgYellow\"")
	}
	if Parameter(44).String() != "BgBlue" {
		t.Errorf("Parameter(44).String() != \"BgBlue\"")
	}
	if Parameter(45).String() != "BgMagenta" {
		t.Errorf("Parameter(45).String() != \"BgMagenta\"")
	}
	if Parameter(46).String() != "BgCyan" {
		t.Errorf("Parameter(46).String() != \"BgCyan\"")
	}
	if Parameter(47).String() != "BgWhite" {
		t.Errorf("Parameter(47).String() != \"BgWhite\"")
	}
	if Parameter(100).String() != "BgBBlack" {
		t.Errorf("Parameter(100).String() != \"BgBBlack\"")
	}
	if Parameter(101).String() != "BgBRed" {
		t.Errorf("Parameter(101).String() != \"BgBRed\"")
	}
	if Parameter(102).String() != "BgBGreen" {
		t.Errorf("Parameter(102).String() != \"BgBGreen\"")
	}
	if Parameter(103).String() != "BgBYellow" {
		t.Errorf("Parameter(103).String() != \"BgBYellow\"")
	}
	if Parameter(104).String() != "BgBBlue" {
		t.Errorf("Parameter(104).String() != \"BgBBlue\"")
	}
	if Parameter(105).String() != "BgBMagenta" {
		t.Errorf("Parameter(105).String() != \"BgBMagenta\"")
	}
	if Parameter(106).String() != "BgBCyan" {
		t.Errorf("Parameter(106).String() != \"BgBCyan\"")
	}
	if Parameter(107).String() != "BgBWhite" {
		t.Errorf("Parameter(107).String() != \"BgBWhite\"")
	}
	// Test the default case.
	if Parameter(255).String() != "Parameter(255)" {
		t.Errorf("Parameter(255).String() != \"Parameter(255)\"")
	}
}

func TestNewParameter(t *testing.T) {
	if NewParameter("Reset") != Parameter(0) {
		t.Errorf("NewParameter(\"Reset\") != Parameter(0)")
	}
	if NewParameter("Bold") != Parameter(1) {
		t.Errorf("NewParameter(\"Bold\") != Parameter(1)")
	}
	if NewParameter("Faint") != Parameter(2) {
		t.Errorf("NewParameter(\"Faint\") != Parameter(2)")
	}
	if NewParameter("Italic") != Parameter(3) {
		t.Errorf("NewParameter(\"Italic\") != Parameter(3)")
	}
	if NewParameter("Underline") != Parameter(4) {
		t.Errorf("NewParameter(\"Underline\") != Parameter(4)")
	}
	if NewParameter("BlinkSlow") != Parameter(5) {
		t.Errorf("NewParameter(\"BlinkSlow\") != Parameter(5)")
	}
	if NewParameter("BlinkRapid") != Parameter(6) {
		t.Errorf("NewParameter(\"BlinkRapid\") != Parameter(6)")
	}
	if NewParameter("ReverseVideo") != Parameter(7) {
		t.Errorf("NewParameter(\"ReverseVideo\") != Parameter(7)")
	}
	if NewParameter("Conceal") != Parameter(8) {
		t.Errorf("NewParameter(\"Conceal\") != Parameter(8)")
	}
	if NewParameter("CrossedOut") != Parameter(9) {
		t.Errorf("NewParameter(\"CrossedOut\") != Parameter(9)")
	}
	if NewParameter("PrimaryFont") != Parameter(10) {
		t.Errorf("NewParameter(\"PrimaryFont\") != Parameter(10)")
	}
	if NewParameter("FgBlack") != Parameter(30) {
		t.Errorf("NewParameter(\"FgBlack\") != Parameter(30)")
	}
	if NewParameter("FgRed") != Parameter(31) {
		t.Errorf("NewParameter(\"FgRed\") != Parameter(31)")
	}
	if NewParameter("FgGreen") != Parameter(32) {
		t.Errorf("NewParameter(\"FgGreen\") != Parameter(32)")
	}
	if NewParameter("FgYellow") != Parameter(33) {
		t.Errorf("NewParameter(\"FgYellow\") != Parameter(33)")
	}
	if NewParameter("FgBlue") != Parameter(34) {
		t.Errorf("NewParameter(\"FgBlue\") != Parameter(34)")
	}
	if NewParameter("FgMagenta") != Parameter(35) {
		t.Errorf("NewParameter(\"FgMagenta\") != Parameter(35)")
	}
	if NewParameter("FgCyan") != Parameter(36) {
		t.Errorf("NewParameter(\"FgCyan\") != Parameter(36)")
	}
	if NewParameter("FgWhite") != Parameter(37) {
		t.Errorf("NewParameter(\"FgWhite\") != Parameter(37)")
	}
	if NewParameter("FgBBlack") != Parameter(90) {
		t.Errorf("NewParameter(\"FgBBlack\") != Parameter(90)")
	}
	if NewParameter("FgBRed") != Parameter(91) {
		t.Errorf("NewParameter(\"FgBRed\") != Parameter(91)")
	}
	if NewParameter("FgBGreen") != Parameter(92) {
		t.Errorf("NewParameter(\"FgBGreen\") != Parameter(92)")
	}
	if NewParameter("FgBYellow") != Parameter(93) {
		t.Errorf("NewParameter(\"FgBYellow\") != Parameter(93)")
	}
	if NewParameter("FgBBlue") != Parameter(94) {
		t.Errorf("NewParameter(\"FgBBlue\") != Parameter(94)")
	}
	if NewParameter("FgBMagenta") != Parameter(95) {
		t.Errorf("NewParameter(\"FgBMagenta\") != Parameter(95)")
	}
	if NewParameter("FgBCyan") != Parameter(96) {
		t.Errorf("NewParameter(\"FgBCyan\") != Parameter(96)")
	}
	if NewParameter("FgBWhite") != Parameter(97) {
		t.Errorf("NewParameter(\"FgBWhite\") != Parameter(97)")
	}
	if NewParameter("BgBlack") != Parameter(40) {
		t.Errorf("NewParameter(\"BgBlack\") != Parameter(40)")
	}
	if NewParameter("BgRed") != Parameter(41) {
		t.Errorf("NewParameter(\"BgRed\") != Parameter(41)")
	}
	if NewParameter("BgGreen") != Parameter(42) {
		t.Errorf("NewParameter(\"BgGreen\") != Parameter(42)")
	}
	if NewParameter("BgYellow") != Parameter(43) {
		t.Errorf("NewParameter(\"BgYellow\") != Parameter(43)")
	}
	if NewParameter("BgBlue") != Parameter(44) {
		t.Errorf("NewParameter(\"BgBlue\") != Parameter(44)")
	}
	if NewParameter("BgMagenta") != Parameter(45) {
		t.Errorf("NewParameter(\"BgMagenta\") != Parameter(45)")
	}
	if NewParameter("BgCyan") != Parameter(46) {
		t.Errorf("NewParameter(\"BgCyan\") != Parameter(46)")
	}
	if NewParameter("BgWhite") != Parameter(47) {
		t.Errorf("NewParameter(\"BgWhite\") != Parameter(47)")
	}
	if NewParameter("BgBBlack") != Parameter(100) {
		t.Errorf("NewParameter(\"BgBBlack\") != Parameter(100)")
	}
	if NewParameter("BgBRed") != Parameter(101) {
		t.Errorf("NewParameter(\"BgBRed\") != Parameter(101)")
	}
	if NewParameter("BgBGreen") != Parameter(102) {
		t.Errorf("NewParameter(\"BgBGreen\") != Parameter(102)")
	}
	if NewParameter("BgBYellow") != Parameter(103) {
		t.Errorf("NewParameter(\"BgBYellow\") != Parameter(103)")
	}
	if NewParameter("BgBBlue") != Parameter(104) {
		t.Errorf("NewParameter(\"BgBBlue\") != Parameter(104)")
	}
	if NewParameter("BgBMagenta") != Parameter(105) {
		t.Errorf("NewParameter(\"BgBMagenta\") != Parameter(105)")
	}
	if NewParameter("BgBCyan") != Parameter(106) {
		t.Errorf("NewParameter(\"BgBCyan\") != Parameter(106)")
	}
	if NewParameter("BgBWhite") != Parameter(107) {
		t.Errorf("NewParameter(\"BgBWhite\") != Parameter(107)")
	}
	// Test the default case.
	if NewParameter("1298498081") != Parameter(0) {
		t.Errorf("NewParameter(\"1298498081\") != Parameter(0)")
	}
}
