on:
  push:
    branches: [ main ]
  pull_request:
name: build
jobs:
  build-test:
    strategy:
      matrix:
        go-version: [ 1.25 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Tools
        run: make tools
      - name: Build
        run: go build -v ./...
      - name: Test Gen
        run: make test_gen
      - name: Test
        run: go test -v ./...  -coverprofile=coverage.txt -covermode=count
      - name: Coverage Report
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.txt
      - name: lint
        uses: golangci/golangci-lint-action@v8
